### PR TITLE
fix invalid page disabled attribute (closes #18)

### LINKED ISSUE #18: Page.js adds invalid "page-disabled"
Page.js is adding page-disabled attribute, which is invalid. It should used "data-page-disabled" and the HTML5 custom data API.  This would also mean updating  newTab.css.

### PR DESCRIPTION
**Pull request by sarracini**
Changed the page-disabled attribute to data-page-disabled in both page.js and newtab.css

### CODE REVIEW

File: js/page.js [hunk 1]
```diff
@@ -159,9 +159,9 @@
       let nodeSelector = "#newtab-grid, #newtab-search-container";
       for (let node of document.querySelectorAll(nodeSelector)) {
         if (aValue) {
-          node.removeAttribute("page-disabled");
+          node.removeAttribute("data-page-disabled");
```
Comment (marcoscaceres) [inline js/page.js]: We should use HTML's custom data API here. 

``` JS
node.data.pageDisabled = null;
```

File: js/page.js [hunk 2]
```diff
@@ -159,9 +159,9 @@
...
         } else {
-          node.setAttribute("page-disabled", "true");
+          node.setAttribute("data-page-disabled", "true");
```
Comment (marcoscaceres) [inline js/page.js]: We should use HTML's custom data API here. 
As above: 

``` JS
node.data.pageDisabled = true;
```

File: js/page.js (hunk 1 above)
Comment (marcoscaceres) [inline js/page.js]: well, probably setting this to `false` is better.

**Comment by marcoscaceres** [comment]
R+
